### ISSUE TITLE
Allow alias in place of index

### ISSUE THREAD

**Issue by MnZrK** [elastic/elasticsearch-river-couchdb#74]
When I point couch river to my 'testdatabase' index, everything is fine.
If I instead create an alias 'testdatabase' pointing to 'testdatabase1' and pass that alias as index to couch river, I receive an error:

    [2014-10-03 14:48:39,129][DEBUG][action.admin.indices.create] [Cassie Lang] [testdatabase] failed to create
    org.elasticsearch.indices.InvalidIndexNameException: [testdatabase] Invalid index name testdatabase], already exists as alias
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:174)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:510)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreateIndexService.java:86)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:209)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:328)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

If the given index is an alias, couch river should use the index it points to rather than attempt to create a new index.

`elasticsearch 1.3.0`
`river-couchdb 2.3.0`

P.S. There was exactly the same issue for mongo river https://github.com/richardwilly98/elasticsearch-river-mongodb/issues/163

**Comment by dadoonet** [comment]
This project has been stopped since elasticsearch 2.0.
